### PR TITLE
Changed folder structure to better support additional PRs in the future

### PR DESCRIPTION
**Pull request by parithon**
This PR adjust the folder structure to support adding new features easier.

Instead of adding multiple module files (.psm1) and adding them as sub-modules within the manifest, I broke them out to individual files (.ps1). I then load all the files into the module's scope when it is first imported. Finally, I only export the functions to the user's scope that are included in the `Export` folder.

This allows others to add new functionality to the module by adding their function to the `Export` folder and then running the script *UpdateManifest* which will make all the prerequisite changes to the manifest file (e.g. find all functions and aliases to export) and bump the version accordingly.

Versioning?!? I took an opinionated approach:

- Whenever the `src/UpdateManifest.ps1` script is run, the 'build' version is bumped.
- Whenever a new function is found in the *Export* folder, the 'minor' version is bumped.
- Finally, if you supply the `-Major` switch to the script, the 'major' version is bumped.

bitmoji

### Adding as a DRAFT to get feedback. Let me know what you think.

### CODE REVIEW

**Comment by michaeljolley** [comment]
I love the idea of separating the scripts and adding future ones via the export.

On the versioning, I think this would be a great GitHub Action.  Rather than performed by the contributor, have a GHA to run when we merge to master that increments build versions based on specific rules.

**Comment by parithon** [comment]
I like the idea of using GitHub actions for the versioning too but I’m not too familiar with them. The Powershell script utilizes builtin cmdlets to update the manifest file and also tests the manifest to ensure it is valid. Not sure if actions can run powershell scripts or not.

**Comment by michaeljolley** [comment]
After the stream with Michael Heap, I'm 100% sold on actions.  I'm setting up actions now to flag/close stale issues/PRs, but you can run pretty much anything you want.  You can even run your action in a container to do whatever (like run powershell) you'd like.

**Review by michaeljolley — APPROVED** [review]
bitmoji

**Pull request merged**
