### PR TITLE
Converted to a Module! Closes #12

### LINKED ISSUE #12: Turn this majestic piece of script into a module

### PR DESCRIPTION
**Pull request by parithon**
**THIS DOES NOT TAKE INTO ACCOUNT THE EXISTING PULL REQUESTS AND THEIR WORK WILL BE MISSING FROM THIS PR**

I converted the ps-alias.ps1 script into a module. Hopefully, the individual files are self-explanatory.

In order to allow the module to load properly, I did have to comment out a couple of functions. See HelperFunctions.psm1 to see which were commented out.

You should be able to publish this with PowerShellGet as well!

Closes #12 

image

### CODE REVIEW

**Comment by corbob** [comment]
Why is `MJAliases.psd1` labeled as a binary file?

**Comment by parithon** [comment]
@corbob I thought that since my laptop saved the file as `UTF-16 LE` I would convert it to `UTF-8`. However, it appears that Github still thinks it is a binary file. Maybe because of the extension?

**Comment by parithon** [comment]
Since I relooked at the changed files Github is now showing the file correctly. So, it was because it was saved as `UTF-16 LE`.

**Review by michaeljolley — APPROVED** [review]

**Comment by michaeljolley** [comment]
bitmoji

**Pull request merged**
